spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
---
spring:
  datasource:
    postgres:
      hikari:
        maxLifetime: 300000
        idleTimeout: 120000
      url: jdbc:postgresql://localhost:5432/freelance_deal
      driverClassName: org.postgresql.Driver
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: ERROR
    org.springframework.web.client.RestTemplate: ERROR
  config:
    activate:
      on-profile: default